//
//  FactualCategories.h
//  SimpleGeo.framework
//
//  Copyright (c) 2010, SimpleGeo Inc.
//  All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//


#pragma mark Factual Categories (Places >= 1.2)

#define FactualCategoryArtsEntertainmentAndNightlife @"Arts, Entertainment & Nightlife"
#define FactualCategoryAdultEntertainment @"Adult Entertainment"
#define FactualCategoryArcadesAndAmusementParks @"Arcades & Amusement Parks"
#define FactualCategoryArtDealersAndGalleries @"Art Dealers & Galleries"
#define FactualCategoryBars @"Bars"
#define FactualCategoryDanceHallsAndSaloons @"Dance Halls & Saloons"
#define FactualCategoryGayBars @"Gay Bars"
#define FactualCategoryHotelLounges @"Hotel Lounges"
#define FactualCategoryPubsandTaverns @"Pubs and Taverns"
#define FactualCategorySportsBars @"Sports Bars"
#define FactualCategoryWineBars @"Wine Bars"
#define FactualCategoryBilliardParlorsAndPoolHalls @"Billiard Parlors & Pool Halls"
#define FactualCategoryBingoHalls @"Bingo Halls"
#define FactualCategoryBowlingAlleys @"Bowling Alleys"
#define FactualCategoryCasinosAndGaming @"Casinos & Gaming"
#define FactualCategoryComedyClubs @"Comedy Clubs"
#define FactualCategoryConcertHallsAndTheaters @"Concert Halls & Theaters"
#define FactualCategoryHookahLounges @"Hookah Lounges"
#define FactualCategoryInternetCafes @"Internet Cafes"
#define FactualCategoryJazzAndBluesCafes @"Jazz & Blues Cafes"
#define FactualCategoryKaraoke @"Karaoke"
#define FactualCategoryMovieTheatres @"Movie Theatres"
#define FactualCategoryMuseums @"Museums"
#define FactualCategoryNightClubs @"Night Clubs"
#define FactualCategoryOrchestrasSymphoniesAndBands @"Orchestras, Symphonies & Bands"
#define FactualCategoryPsychicsAndAstrologers @"Psychics & Astrologers"
#define FactualCategorySocialClubs @"Social Clubs"
#define FactualCategoryTicketSales @"Ticket Sales"
#define FactualCategoryAutomotive @"Automotive"
#define FactualCategoryAutoRepair @"Auto Repair"
#define FactualCategoryCarAppraisers @"Car Appraisers"
#define FactualCategoryCarDealers @"Car Dealers"
#define FactualCategoryCarLeasing @"Car Leasing"
#define FactualCategoryCarPartsAndAccessories @"Car Parts & Accessories"
#define FactualCategoryCarRentals @"Car Rentals"
#define FactualCategoryCarWashAndDetail @"Car Wash & Detail"
#define FactualCategoryClassicAndAntiqueCar @"Classic & Antique Car"
#define FactualCategoryMotorcyclesRepair @"Motorcycles Repair"
#define FactualCategoryMotorcyclesMopedsAndScooters @"Motorcycles, Mopeds & Scooters"
#define FactualCategoryNewCars @"New Cars"
#define FactualCategoryOilAndLube @"Oil & Lube"
#define FactualCategoryRVsAndMotorHomes @"RVs & Motor Homes"
#define FactualCategorySmogCheck @"Smog Check"
#define FactualCategorySnowmobiles @"Snowmobiles"
#define FactualCategoryTires @"Tires"
#define FactualCategoryTowing @"Towing"
#define FactualCategoryTransmissions @"Transmissions"
#define FactualCategoryUsedAutoPartsAndSalvageYards @"Used Auto Parts & Salvage Yards"
#define FactualCategoryUsedCars @"Used Cars"
#define FactualCategoryBusinessAndProfessionalServices @"Business & Professional Services"
#define FactualCategoryAdvertisingAndMarketing @"Advertising & Marketing"
#define FactualCategoryAdvertisingAgenciesAndMediaBuyers @"Advertising Agencies & Media Buyers"
#define FactualCategoryCoupons @"Coupons"
#define FactualCategoryCreativeServices @"Creative Services"
#define FactualCategoryDirectMailAndEmailMarketingServices @"Direct Mail & Email Marketing Services"
#define FactualCategoryLeadGenerationAndMarketingLists @"Lead Generation & Marketing Lists"
#define FactualCategoryMarketResearchAndMarketingConsultants @"Market Research & Marketing Consultants"
#define FactualCategoryOnlineAdvertising @"Online Advertising"
#define FactualCategoryPrintTVRadioAndOutdoorAdvertising @"Print, TV, Radio & Outdoor Advertising"
#define FactualCategoryPrintingCopyingAndSignage @"Printing, Copying & Signage"
#define FactualCategoryPromotionalItems @"Promotional Items"
#define FactualCategoryPublicRelations @"Public Relations"
#define FactualCategorySearchEngineMarketingAndOptimization @"Search Engine Marketing & Optimization"
#define FactualCategoryWebDesignAndDevelopment @"Web Design & Development"
#define FactualCategoryWritingCopywritingAndTechnicalWriting @"Writing, Copywriting & Technical Writing"
#define FactualCategoryBusinessCenters @"Business Centers"
#define FactualCategoryEmploymentAgencies @"Employment Agencies"
#define FactualCategoryEntertainment @"Entertainment"
#define FactualCategoryEquipmentSuppliesAndServices @"Equipment, Supplies & Services"
#define FactualCategoryAudiovisual @"Audiovisual"
#define FactualCategoryAutomationAndControlSystems @"Automation & Control Systems"
#define FactualCategoryChemicalsAndGasses @"Chemicals & Gasses"
#define FactualCategoryComputers @"Computers"
#define FactualCategoryFoodAndBeverage @"Food & Beverage"
#define FactualCategoryGeological @"Geological"
#define FactualCategoryHairAndBeauty @"Hair & Beauty"
#define FactualCategoryIndustrialMachineryAndVehicles @"Industrial Machinery & Vehicles"
#define FactualCategoryLoggingAndSawmills @"Logging & Sawmills"
#define FactualCategoryMachineShops @"Machine Shops"
#define FactualCategoryMetals @"Metals"
#define FactualCategoryPackaging @"Packaging"
#define FactualCategoryPetroleum @"Petroleum"
#define FactualCategoryPlastics @"Plastics"
#define FactualCategoryRefrigerationAndIce @"Refrigeration & Ice"
#define FactualCategoryRubber @"Rubber"
#define FactualCategoryScientific @"Scientific"
#define FactualCategoryShippingAndFreight @"Shipping & Freight"
#define FactualCategoryTextiles @"Textiles"
#define FactualCategoryWaterAndWasteManagement @"Water & Waste Management"
#define FactualCategoryWelding @"Welding"
#define FactualCategoryManagement @"Management"
#define FactualCategoryWholesale @"Wholesale"
#define FactualCategoryCommunityAndGovernment @"Community & Government"
#define FactualCategoryAnimalSheltersAndHumaneSocieties @"Animal Shelters & Humane Societies"
#define FactualCategoryCaretakers @"Caretakers"
#define FactualCategoryCemeteries @"Cemeteries"
#define FactualCategoryDayCareAndPreschools @"Day Care & Preschools"
#define FactualCategoryDisabledPersonsServices @"Disabled Persons Services"
#define FactualCategoryDrugAndAlcoholResources @"Drug & Alcohol Resources"
#define FactualCategoryDryCleaningIroningAndLaundry @"Dry Cleaning, Ironing & Laundry"
#define FactualCategoryEmergencyAndDisasterPreparednessServices @"Emergency & Disaster Preparedness Services"
#define FactualCategoryEnvironmentalConservationAndEcologicalOrganizations @"Environmental Conservation & Ecological Organizations"
#define FactualCategoryHousingAssistanceAndShelters @"Housing Assistance & Shelters"
#define FactualCategoryLawEnforcementAndPublicSafety @"Law Enforcement & Public Safety"
#define FactualCategoryFireStations @"Fire Stations"
#define FactualCategoryPoliceStations @"Police Stations"
#define FactualCategoryLibraries @"Libraries"
#define FactualCategoryOrganizationsAndAssociations @"Organizations & Associations"
#define FactualCategoryPolitics @"Politics"
#define FactualCategoryGovernmentLobbyists @"Government Lobbyists"
#define FactualCategoryPostOffices @"Post Offices"
#define FactualCategoryPublicAndSocialServices @"Public & Social Services"
#define FactualCategoryReligious @"Religious"
#define FactualCategoryBuddhistTemples @"Buddhist Temples"
#define FactualCategoryChurches @"Churches"
#define FactualCategoryHinduTemples @"Hindu Temples"
#define FactualCategoryMosques @"Mosques"
#define FactualCategorySynagogues @"Synagogues"
#define FactualCategoryRescueServices @"Rescue Services"
#define FactualCategoryRetirementAndAssistedLivingFacilities @"Retirement & Assisted Living Facilities"
#define FactualCategorySeniorCitizenCentersAndServices @"Senior Citizen Centers & Services"
#define FactualCategoryYouthOrganizations @"Youth Organizations"
#define FactualCategoryEducation @"Education"
#define FactualCategoryAdultEducation @"Adult Education"
#define FactualCategoryArtInstructionAndSchools @"Art Instruction & Schools"
#define FactualCategoryCollegesAndUniversities @"Colleges & Universities"
#define FactualCategoryComputerTraining @"Computer Training"
#define FactualCategoryCulinarySchoolsAndCookingLessons @"Culinary Schools & Cooking Lessons"
#define FactualCategoryDanceInstruction @"Dance Instruction"
#define FactualCategoryDrivingSchool @"Driving School"
#define FactualCategoryEducationalServices @"Educational Services"
#define FactualCategoryFraternitiesAndSororities @"Fraternities & Sororities"
#define FactualCategoryGymnasticsInstruction @"Gymnastics Instruction"
#define FactualCategoryHealthAndMedicineEducation @"Health & Medicine Education"
#define FactualCategorySchools @"Schools"
#define FactualCategoryTestPrepAndTutors @"Test Prep & Tutors"
#define FactualCategoryVocationalSchools @"Vocational Schools"
#define FactualCategoryBagelsAndDonuts @"Bagels & Donuts"
#define FactualCategoryBakeries @"Bakeries"
#define FactualCategoryBeerWineAndSpirits @"Beer, Wine & Spirits"
#define FactualCategoryBreweries @"Breweries"
#define FactualCategoryCafesCoffeeHousesAndTeaHouses @"Cafes, Coffee Houses & Tea Houses"
#define FactualCategoryCheese @"Cheese"
#define FactualCategoryChocolate @"Chocolate"
#define FactualCategoryDessert @"Dessert"
#define FactualCategoryEthnicFood @"Ethnic Food"
#define FactualCategoryFarmersMarkets @"Farmers' Markets"
#define FactualCategoryHealthAndDietFood @"Health & Diet Food"
#define FactualCategoryIceCreamParlors @"Ice Cream Parlors"
#define FactualCategoryJuiceBarsAndSmoothies @"Juice Bars & Smoothies"
#define FactualCategoryKosher @"Kosher"
#define FactualCategoryRestaurants @"Restaurants"
#define FactualCategoryAmerican @"American"
#define FactualCategoryBarbecue @"Barbecue"
#define FactualCategoryBuffets @"Buffets"
#define FactualCategoryBurgers @"Burgers"
#define FactualCategoryChinese @"Chinese"
#define FactualCategoryDelis @"Delis"
#define FactualCategoryDiners @"Diners"
#define FactualCategoryFastFood @"Fast Food"
#define FactualCategoryFrench @"French"
#define FactualCategoryIndian @"Indian"
#define FactualCategoryItalian @"Italian"
#define FactualCategoryJapanese @"Japanese"
#define FactualCategoryKorean @"Korean"
#define FactualCategoryMexican @"Mexican"
#define FactualCategoryMiddleEastern @"Middle Eastern"
#define FactualCategoryPizza @"Pizza"
#define FactualCategorySeafood @"Seafood"
#define FactualCategorySteakhouses @"Steakhouses"
#define FactualCategorySushi @"Sushi"
#define FactualCategoryThai @"Thai"
#define FactualCategoryVeganAndVegetarian @"Vegan & Vegetarian"
#define FactualCategoryHealthAndMedicine @"Health & Medicine"
#define FactualCategoryAbortionServices @"Abortion Services"
#define FactualCategoryAIDSResources @"AIDS Resources"
#define FactualCategoryAmbulanceService @"Ambulance Service"
#define FactualCategoryBirthControlInformationAndServices @"Birth Control Information & Services"
#define FactualCategoryBloodBanksAndCenters @"Blood Banks & Centers"
#define FactualCategoryDentists @"Dentists"
#define FactualCategoryDietAndNutritionists @"Diet & Nutritionists"
#define FactualCategoryHealthServices @"Health Services"
#define FactualCategoryHolisticAlternativeAndNaturopathicMedicine @"Holistic, Alternative & Naturopathic Medicine"
#define FactualCategoryAcupuncture @"Acupuncture"
#define FactualCategoryChiropractors @"Chiropractors"
#define FactualCategoryHospitalsClinicsAndMedicalCenters @"Hospitals, Clinics & Medical Centers"
#define FactualCategoryMedicalSuppliesAndLabs @"Medical Supplies & Labs"
#define FactualCategoryMentalHealthServices @"Mental Health Services"
#define FactualCategoryCounseling @"Counseling"
#define FactualCategoryNurses @"Nurses"
#define FactualCategoryNursingHomes @"Nursing Homes"
#define FactualCategoryPharmacies @"Pharmacies"
#define FactualCategoryPhysicalTherapyAndRehabilitation @"Physical Therapy & Rehabilitation"
#define FactualCategoryPhysicians @"Physicians"
#define FactualCategoryAnesthesiologists @"Anesthesiologists"
#define FactualCategoryCardiologists @"Cardiologists"
#define FactualCategoryDermatologists @"Dermatologists"
#define FactualCategoryEarNoseAndThroat @"Ear, Nose & Throat"
#define FactualCategoryFamilyMedicine @"Family Medicine"
#define FactualCategoryInternalMedicine @"Internal Medicine"
#define FactualCategoryObstetriciansAndGynecologists @"Obstetricians & Gynecologists"
#define FactualCategoryOncologists @"Oncologists"
#define FactualCategoryOphthalmologists @"Ophthalmologists"
#define FactualCategoryOrthopedicSurgeons @"Orthopedic Surgeons"
#define FactualCategoryPediatricians @"Pediatricians"
#define FactualCategoryPlasticSurgeons @"Plastic Surgeons"
#define FactualCategoryPodiatrists @"Podiatrists"
#define FactualCategoryPsychiatrists @"Psychiatrists"
#define FactualCategorySportsMedicine @"Sports Medicine"
#define FactualCategoryPregnancyAndChildbirthServices @"Pregnancy & Childbirth Services"
#define FactualCategoryVeterinarians @"Veterinarians"
#define FactualCategoryLegalAndFinancial @"Legal & Financial"
#define FactualCategoryAccountingAndBookkeeping @"Accounting & Bookkeeping"
#define FactualCategoryBankingAndFinancing @"Banking & Financing"
#define FactualCategoryBusinessAndStrategyConsulting @"Business & Strategy Consulting"
#define FactualCategoryBusinessBrokersAndFranchises @"Business Brokers & Franchises"
#define FactualCategoryCheckCashing @"Check Cashing"
#define FactualCategoryCollections @"Collections"
#define FactualCategoryCreditCounselingAndBankruptcyServices @"Credit Counseling & Bankruptcy Services"
#define FactualCategoryFinancialPlanningAndInvestments @"Financial Planning & Investments"
#define FactualCategoryFundRaisingAndFinancialAid @"Fund Raising & Financial Aid"
#define FactualCategoryImmigrationServices @"Immigration Services"
#define FactualCategoryInsurance @"Insurance"
#define FactualCategoryLawyersAndLegalServices @"Lawyers & Legal Services"
#define FactualCategoryLoansAndMortgages @"Loans & Mortgages"
#define FactualCategoryMerchantSolutions @"Merchant Solutions"
#define FactualCategorySavingsAndLoanAssociations @"Savings & Loan Associations"
#define FactualCategoryPersonalCareAndServices @"Personal Care & Services"
#define FactualCategoryBeautyAndSkinCare @"Beauty & Skin Care"
#define FactualCategoryDaySpasAndDestinationSpas @"Day Spas & Destination Spas"
#define FactualCategoryHairRemoval @"Hair Removal"
#define FactualCategoryHairSalonsAndBarbers @"Hair Salons & Barbers"
#define FactualCategoryManicuresAndPedicures @"Manicures & Pedicures"
#define FactualCategoryMassageClinicsAndTherapists @"Massage Clinics & Therapists"
#define FactualCategoryPiercing @"Piercing"
#define FactualCategoryTanningSalons @"Tanning Salons"
#define FactualCategoryTattooing @"Tattooing"
#define FactualCategoryWigsHairpiecesAndExtensions @"Wigs, Hairpieces & Extensions"
#define FactualCategoryRealEstateAndHomeImprovement @"Real Estate & Home Improvement"
#define FactualCategoryApartmentsAndCondos @"Apartments & Condos"
#define FactualCategoryBoardingHouses @"Boarding Houses"
#define FactualCategoryBuildingAndLandSurveyors @"Building & Land Surveyors"
#define FactualCategoryCarpenters @"Carpenters"
#define FactualCategoryCarpetAndFlooring @"Carpet & Flooring"
#define FactualCategoryCommercialRealEstate @"Commercial Real Estate"
#define FactualCategoryConstructionSupplies @"Construction Supplies"
#define FactualCategoryContractors @"Contractors"
#define FactualCategoryDeckAndPatio @"Deck & Patio"
#define FactualCategorySewer @"Sewer"
#define FactualCategoryCorporateHousing @"Corporate Housing"
#define FactualCategoryElectricians @"Electricians"
#define FactualCategoryFencesFireplacesAndGarageDoors @"Fences, Fireplaces & Garage Doors"
#define FactualCategoryHardwareAndServices @"Hardware & Services"
#define FactualCategoryHeatingVentilatingAndAirConditioning @"Heating, Ventilating & Air Conditioning"
#define FactualCategoryHomeAppliances @"Home Appliances"
#define FactualCategoryHomeAppraiser @"Home Appraiser"
#define FactualCategoryHomeCleaning @"Home Cleaning"
#define FactualCategoryHomeInspectionServices @"Home Inspection Services"
#define FactualCategoryHousewares @"Housewares"
#define FactualCategoryInteriorDesign @"Interior Design"
#define FactualCategoryKitchens @"Kitchens"
#define FactualCategoryLandscapingAndGardeners @"Landscaping & Gardeners"
#define FactualCategoryLightingFixtures @"Lighting Fixtures"
#define FactualCategoryMobileHomes @"Mobile Homes"
#define FactualCategoryMovers @"Movers"
#define FactualCategoryPainting @"Painting"
#define FactualCategoryPestControl @"Pest Control"
#define FactualCategoryPlumbing @"Plumbing"
#define FactualCategoryPoolsAndSpas @"Pools & Spas"
#define FactualCategoryPropertyManagement @"Property Management"
#define FactualCategoryRealEstateAgents @"Real Estate Agents"
#define FactualCategoryRealEstateDevelopmentAndTitleCompanies @"Real Estate Development & Title Companies"
#define FactualCategoryRoofers @"Roofers"
#define FactualCategorySolarEnergy @"Solar Energy"
#define FactualCategoryStorage @"Storage"
#define FactualCategorySwimmingPoolMaintenanceAndServices @"Swimming Pool Maintenance & Services"
#define FactualCategoryTreeService @"Tree Service"
#define FactualCategoryUpholstery @"Upholstery"
#define FactualCategoryWindows @"Windows"
#define FactualCategoryShopping @"Shopping"
#define FactualCategoryAdultShopping @"Adult Shopping"
#define FactualCategoryAntiques @"Antiques"
#define FactualCategoryArtRestoration @"Art Restoration"
#define FactualCategoryArtsAndCraftsSupplies @"Arts & Crafts Supplies"
#define FactualCategoryATMs @"ATMs"
#define FactualCategoryAuctions @"Auctions"
#define FactualCategoryBeautyProducts @"Beauty Products"
#define FactualCategoryBicycleSalesAndService @"Bicycle Sales & Service"
#define FactualCategoryBookstores @"Bookstores"
#define FactualCategoryCamerasAndPhotosAndFrames @"Cameras & Photos & Frames"
#define FactualCategoryCandyStores @"Candy Stores"
#define FactualCategoryCardsAndStationery @"Cards & Stationery"
#define FactualCategoryChildrensProducts @"Children's Products"
#define FactualCategoryComputersAndElectronics @"Computers & Electronics"
#define FactualCategoryCostumes @"Costumes"
#define FactualCategoryDanceSupplies @"Dance Supplies"
#define FactualCategoryDepartmentStores @"Department Stores"
#define FactualCategoryDiscountStoresWarehousesAndWholesaleStores @"Discount Stores, Warehouses & Wholesale Stores"
#define FactualCategoryFashion @"Fashion"
#define FactualCategoryClothingAndAccessories @"Clothing & Accessories"
#define FactualCategoryJewelryAndWatches @"Jewelry & Watches"
#define FactualCategoryShoes @"Shoes"
#define FactualCategorySwimwear @"Swimwear"
#define FactualCategoryFleaMarkets @"Flea Markets"
#define FactualCategoryFlorists @"Florists"
#define FactualCategoryFurniture @"Furniture"
#define FactualCategoryGasStationsAndConvenienceStores @"Gas Stations & Convenience Stores"
#define FactualCategoryGiftAndNoveltyStores @"Gift & Novelty Stores"
#define FactualCategoryGlassesAndOptometrist @"Glasses & Optometrist"
#define FactualCategoryHobbyCollectiblesAndCraftStores @"Hobby, Collectibles & Craft Stores"
#define FactualCategoryLuggage @"Luggage"
#define FactualCategoryMusic @"Music"
#define FactualCategoryNewsstands @"Newsstands"
#define FactualCategoryNurseriesAndGardenCenters @"Nurseries & Garden Centers"
#define FactualCategoryOutletStores @"Outlet Stores"
#define FactualCategoryPawnShops @"Pawn Shops"
#define FactualCategoryPetShopsAndPetSupplies @"Pet Shops & Pet Supplies"
#define FactualCategoryShoppingCentersAndMalls @"Shopping Centers & Malls"
#define FactualCategorySportingGoods @"Sporting Goods"
#define FactualCategorySupermarketsAndGroceries @"Supermarkets & Groceries"
#define FactualCategoryTailors @"Tailors"
#define FactualCategoryTobaccoShops @"Tobacco Shops"
#define FactualCategoryToyStores @"Toy Stores"
#define FactualCategoryVideoRental @"Video Rental"
#define FactualCategoryVintageStoresAndThriftShops @"Vintage Stores & Thrift Shops"
#define FactualCategoryWeddingAndBridalShops @"Wedding & Bridal Shops"
#define FactualCategorySportsAndRecreationAndnbsp @"Sports & Recreation&nbsp;"
#define FactualCategoryArchery @"Archery"
#define FactualCategoryBaseball @"Baseball"
#define FactualCategoryBattingRanges @"Batting Ranges"
#define FactualCategoryBicycleRentals @"Bicycle Rentals"
#define FactualCategoryBoatChartersAndRentals @"Boat Charters & Rentals"
#define FactualCategoryBotanicalGardens @"Botanical Gardens"
#define FactualCategoryCarnivals @"Carnivals"
#define FactualCategoryCircuses @"Circuses"
#define FactualCategoryFairgroundsAndRodeos @"Fairgrounds & Rodeos"
#define FactualCategoryFootball @"Football"
#define FactualCategoryGoCarts @"Go Carts"
#define FactualCategoryGunRanges @"Gun Ranges"
#define FactualCategoryGymsAndFitnessCenters @"Gyms & Fitness Centers"
#define FactualCategoryHockey @"Hockey"
#define FactualCategoryIceSkating @"Ice Skating"
#define FactualCategoryMartialArts @"Martial Arts"
#define FactualCategoryMiniatureGolf @"Miniature Golf"
#define FactualCategoryOutdoorRecreation @"Outdoor Recreation"
#define FactualCategoryBeaches @"Beaches"
#define FactualCategoryCampgroundsAndRVParks @"Campgrounds & RV Parks"
#define FactualCategoryCanoesAndKayaks @"Canoes & Kayaks"
#define FactualCategoryGolf @"Golf"
#define FactualCategoryHiking @"Hiking"
#define FactualCategoryHotAirBalloons @"Hot Air Balloons"
#define FactualCategoryHuntingAndFishing @"Hunting & Fishing"
#define FactualCategoryLakes @"Lakes"
#define FactualCategoryParks @"Parks"
#define FactualCategoryPicnicAreas @"Picnic Areas"
#define FactualCategoryRafting @"Rafting"
#define FactualCategoryRockClimbing @"Rock Climbing"
#define FactualCategoryScubaDiving @"Scuba Diving"
#define FactualCategorySkiAndSnowboard @"Ski & Snowboard"
#define FactualCategoryWaterSports @"Water Sports"
#define FactualCategoryPaintball @"Paintball"
#define FactualCategoryPartyCenters @"Party Centers"
#define FactualCategoryPersonalTrainers @"Personal Trainers"
#define FactualCategoryPlaygrounds @"Playgrounds"
#define FactualCategoryRaceTracks @"Race Tracks"
#define FactualCategoryRacquetball @"Racquetball"
#define FactualCategorySkydiving @"Skydiving"
#define FactualCategorySoccerClubsAndInstruction @"Soccer Clubs & Instruction"
#define FactualCategorySportsAndRecreationCenters @"Sports & Recreation Centers"
#define FactualCategorySportsClubs @"Sports Clubs"
#define FactualCategorySportsInstruction @"Sports Instruction"
#define FactualCategoryStadiumsArenasAndAthleticFields @"Stadiums, Arenas & Athletic Fields"
#define FactualCategorySwimmingPools @"Swimming Pools"
#define FactualCategoryTennis @"Tennis"
#define FactualCategoryYogaAndPilates @"Yoga & Pilates"
#define FactualCategoryZoosAquariumsAndWildlifeSanctuaries @"Zoos, Aquariums & Wildlife Sanctuaries"
#define FactualCategoryTravelAndTourism @"Travel & Tourism"
#define FactualCategoryAirlines @"Airlines"
#define FactualCategoryAirports @"Airports"
#define FactualCategoryCharterAndPrivatePlanes @"Charter & Private Planes"
#define FactualCategoryCruises @"Cruises"
#define FactualCategoryHistoricalSites @"Historical Sites"
#define FactualCategoryHorseDrawnVehicles @"Horse-Drawn Vehicles"
#define FactualCategoryLodging @"Lodging"
#define FactualCategoryBedAndBreakfasts @"Bed & Breakfasts"
#define FactualCategoryCottagesAndCabins @"Cottages & Cabins"
#define FactualCategoryHostels @"Hostels"
#define FactualCategoryHotelsAndMotels @"Hotels & Motels"
#define FactualCategoryLodgesAndVacationRentals @"Lodges & Vacation Rentals"
#define FactualCategoryMonuments @"Monuments"
#define FactualCategoryParking @"Parking"
#define FactualCategoryPublicTransportationAndTransit @"Public Transportation & Transit"
#define FactualCategoryRailroadsAndTrains @"Railroads & Trains"
#define FactualCategoryResorts @"Resorts"
#define FactualCategoryTaxiAndCarServices @"Taxi & Car Services"
#define FactualCategoryCharterBuses @"Charter Buses"
#define FactualCategoryLimosAndChauffers @"Limos & Chauffers"
#define FactualCategoryTouristAttractions @"Tourist Attractions"
#define FactualCategoryTouristInformationAndServices @"Tourist Information & Services"
#define FactualCategoryTravelAgentsAndTourOperators @"Travel Agents & Tour Operators"
#define FactualCategoryWineriesAndVineyards @"Wineries & Vineyards"
