//
//  SGCategories.h
//  SimpleGeo.framework
//
//  Copyright (c) 2010, SimpleGeo Inc.
//  All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

typedef NSString * SGFeatureType;
typedef NSString * SGFeatureCategory;
typedef NSString * SGFeatureSubcategory;

#pragma mark -
#pragma mark Feature Types (Context)

#define SGFeatureTypeRegion @"Region"
#define SGFeatureTypeEntertainment @"Entertainment"
#define SGFeatureTypeFoodAndDrink @"Food & Drink"
#define SGFeatureTypeManufacturingAndWholesaleGoods @"Manufacturing & Wholesale Goods"
#define SGFeatureTypePhysicalFeature @"Physical Feature"
#define SGFeatureTypePublicPlace @"Public Place"
#define SGFeatureTypeRetailGoods @"Retail Goods"
#define SGFeatureTypeServices @"Services"
#define SGFeatureTypeTransportation @"Transportation"

#pragma mark -
#pragma mark Feature Categories (Context)

#define SGFeatureCategoryAdministrative @"Administrative"
#define SGFeatureCategoryCommercialArea @"Commercial Area"
#define SGFeatureCategoryDMA @"DMA"
#define SGFeatureCategoryLegislativeDistrict @"Legislative District"
#define SGFeatureCategoryLocality @"Locality"
#define SGFeatureCategoryMunicipality @"Municipality"
#define SGFeatureCategoryNational @"National"
#define SGFeatureCategoryNeighborhood @"Neighborhood"
#define SGFeatureCategoryPostalCode @"Postal Code"
#define SGFeatureCategoryProtectedArea @"Protected Area"
#define SGFeatureCategoryRegion @"Region"
#define SGFeatureCategoryResidentialArea @"Residential Area"
#define SGFeatureCategorySchoolDistrict @"School District"
#define SGFeatureCategorySubnational @"Subnational"
#define SGFeatureCategoryTimeZone @"Time Zone"
#define SGFeatureCategoryUSCensus @"US Census"

#pragma mark -
#pragma mark Feature Subcategories (Context)

#define SGFeatureSubcategoryConsolidatedCity @"Consolidated City"
#define SGFeatureSubcategoryCounty @"County"
#define SGFeatureSubcategoryParish @"Parish"
#define SGFeatureSubcategoryBusinessDistrict @"Business District"
#define SGFeatureSubcategoryOfficePark @"Office Park"
#define SGFeatureSubcategoryMunicipal @"Municipal"
#define SGFeatureSubcategoryNational @"National"
#define SGFeatureSubcategoryProvincialLower @"Provincial (Lower)"
#define SGFeatureSubcategoryProvincialUpper @"Provincial (Upper)"
#define SGFeatureSubcategoryBorough @"Borough"
#define SGFeatureSubcategoryCity @"City"
#define SGFeatureSubcategoryHamlet @"Hamlet"
#define SGFeatureSubcategorySubdivision @"Subdivision"
#define SGFeatureSubcategorySuburb @"Suburb"
#define SGFeatureSubcategoryTown @"Town"
#define SGFeatureSubcategoryVillage @"Village"
#define SGFeatureSubcategoryCountry @"Country"
#define SGFeatureSubcategoryTerritory @"Territory"
#define SGFeatureSubcategoryForest @"Forest"
#define SGFeatureSubcategoryNatureReserve @"Nature Reserve"
#define SGFeatureSubcategoryPrimary @"Primary"
#define SGFeatureSubcategorySecondary @"Secondary"
#define SGFeatureSubcategoryUnified @"Unified"
#define SGFeatureSubcategoryProvince @"Province"
#define SGFeatureSubcategoryState @"State"
#define SGFeatureSubcategoryBlock @"Block"
#define SGFeatureSubcategoryBlockGroup @"Block Group"
#define SGFeatureSubcategoryMSA @"MSA"
#define SGFeatureSubcategoryTract @"Tract"

#pragma mark -
#pragma mark Places Categories (Places 1.0)

#define SGPlaceCategoryArena @"Arena"
#define SGPlaceCategoryArtsAndPerformance @"Arts & Performance"
#define SGPlaceCategoryCasinosAndGambling @"Casinos & Gambling"
#define SGPlaceCategoryCinema @"Cinema"
#define SGPlaceCategoryMuseum @"Museum"
#define SGPlaceCategoryRecreation @"Recreation"
#define SGPlaceCategorySportsAndExercise @"Sports & Exercise"
#define SGPlaceCategoryTravel @"Travel"
#define SGPlaceCategoryBagels @"Bagels"
#define SGPlaceCategoryBakery @"Bakery"
#define SGPlaceCategoryBarsAndPubs @"Bars & Pubs"
#define SGPlaceCategoryBrewery @"Brewery"
#define SGPlaceCategoryCafe @"Cafe"
#define SGPlaceCategoryCoffeeAndTea @"Coffee & Tea"
#define SGPlaceCategoryDeli @"Deli"
#define SGPlaceCategoryDistillery @"Distillery"
#define SGPlaceCategoryDonuts @"Donuts"
#define SGPlaceCategoryFastFood @"Fast Food"
#define SGPlaceCategoryFoodCourt @"Food Court"
#define SGPlaceCategoryIceCream @"Ice Cream"
#define SGPlaceCategoryInternetCafe @"Internet Cafe"
#define SGPlaceCategoryJuiceBar @"Juice Bar"
#define SGPlaceCategoryRestaurant @"Restaurant"
#define SGPlaceCategoryTeaRoom @"Tea Room"
#define SGPlaceCategoryWinery @"Winery"
#define SGPlaceCategoryFarming @"Farming"
#define SGPlaceCategoryManufacturing @"Manufacturing"
#define SGPlaceCategoryMiningAndDrilling @"Mining & Drilling"
#define SGPlaceCategoryWholesale @"Wholesale"
#define SGPlaceCategoryBasin @"Basin"
#define SGPlaceCategoryBeach @"Beach"
#define SGPlaceCategoryCanyon @"Canyon"
#define SGPlaceCategoryForest @"Forest"
#define SGPlaceCategoryGrassland @"Grassland"
#define SGPlaceCategoryIsland @"Island"
#define SGPlaceCategoryLake @"Lake"
#define SGPlaceCategoryLandfill @"Landfill"
#define SGPlaceCategoryMine @"Mine"
#define SGPlaceCategoryMountain @"Mountain"
#define SGPlaceCategoryPond @"Pond"
#define SGPlaceCategoryQuarry @"Quarry"
#define SGPlaceCategoryReservoir @"Reservoir"
#define SGPlaceCategoryWell @"Well"
#define SGPlaceCategoryAnimalShelter @"Animal Shelter"
#define SGPlaceCategoryCemetery @"Cemetery"
#define SGPlaceCategoryCommercialArea @"Commercial Area"
#define SGPlaceCategoryCommunityCenter @"Community Center"
#define SGPlaceCategoryConferenceCenter @"Conference Center"
#define SGPlaceCategoryEducation @"Education"
#define SGPlaceCategoryExhibitionHall @"Exhibition Hall"
#define SGPlaceCategoryGovernment @"Government"
#define SGPlaceCategoryIndustrialArea @"Industrial Area"
#define SGPlaceCategoryLandmark @"Landmark"
#define SGPlaceCategoryMilitaryArea @"Military Area"
#define SGPlaceCategoryPark @"Park"
#define SGPlaceCategoryPlaceofWorship @"Place of Worship"
#define SGPlaceCategoryScienceFacility @"Science Facility"
#define SGPlaceCategoryShoppingCenter @"Shopping Center"
#define SGPlaceCategoryStructure @"Structure"
#define SGPlaceCategoryAutosAndMotorVehicles @"Autos & Motor Vehicles"
#define SGPlaceCategoryFoodAndBeverages @"Food & Beverages"
#define SGPlaceCategoryHomeAndGarden @"Home & Garden"
#define SGPlaceCategoryShopping @"Shopping"
#define SGPlaceCategoryBanksAndCreditUnions @"Banks & Credit Unions"
#define SGPlaceCategoryBuildingAndTrades @"Building & Trades"
#define SGPlaceCategoryCommunications @"Communications"
#define SGPlaceCategoryHealthServices @"Health Services"
#define SGPlaceCategoryInsurance @"Insurance"
#define SGPlaceCategoryOrganizations @"Organizations"
#define SGPlaceCategoryPersonal @"Personal"
#define SGPlaceCategoryProfessional @"Professional"
#define SGPlaceCategoryRealEstate @"Real Estate"
#define SGPlaceCategoryRetail @"Retail"
#define SGPlaceCategorySocialServices @"Social Services"
#define SGPlaceCategoryUtilities @"Utilities"
#define SGPlaceCategoryAirline @"Airline"
#define SGPlaceCategoryAirport @"Airport"
#define SGPlaceCategoryBusCharters @"Bus Charters"
#define SGPlaceCategoryBusStation @"Bus Station"
#define SGPlaceCategoryBusStop @"Bus Stop"
#define SGPlaceCategoryDepot @"Depot"
#define SGPlaceCategoryFerry @"Ferry"
#define SGPlaceCategoryFerryTerminal @"Ferry Terminal"
#define SGPlaceCategoryFreight @"Freight"
#define SGPlaceCategoryHarbor @"Harbor"
#define SGPlaceCategoryLocalTransit @"Local Transit"
#define SGPlaceCategoryMarine @"Marine"
#define SGPlaceCategoryMetroStation @"Metro Station"
#define SGPlaceCategoryParking @"Parking"
#define SGPlaceCategoryRailroad @"Railroad"
#define SGPlaceCategorySchoolBuses @"School Buses"
#define SGPlaceCategoryTaxi @"Taxi"
#define SGPlaceCategoryTrainStation @"Train Station"
#define SGPlaceCategoryTransitCenter @"Transit Center"
#define SGPlaceCategoryAutoRacetrack @"Auto Racetrack"
#define SGPlaceCategoryBullRing @"Bull Ring"
#define SGPlaceCategoryHorseRacetrack @"Horse Racetrack"
#define SGPlaceCategoryIndoorArena @"Indoor Arena"
#define SGPlaceCategorySportsClub @"Sports Club"
#define SGPlaceCategoryStadium @"Stadium"
#define SGPlaceCategoryArtGallery @"Art Gallery"
#define SGPlaceCategoryArtsCenter @"Arts Center"
#define SGPlaceCategoryCircus @"Circus"
#define SGPlaceCategoryDance @"Dance"
#define SGPlaceCategoryFestival @"Festival"
#define SGPlaceCategoryJazzAndBlues @"Jazz & Blues"
#define SGPlaceCategoryMusic @"Music"
#define SGPlaceCategoryOpera @"Opera"
#define SGPlaceCategorySymphony @"Symphony"
#define SGPlaceCategoryTheater @"Theater"
#define SGPlaceCategoryComedyClub @"Comedy Club"
#define SGPlaceCategoryDriveInTheater @"Drive-In Theater"
#define SGPlaceCategoryMovieRental @"Movie Rental"
#define SGPlaceCategoryMovieTheater @"Movie Theater"
#define SGPlaceCategoryAquarium @"Aquarium"
#define SGPlaceCategoryArtMuseum @"Art Museum"
#define SGPlaceCategoryBotanicalGarden @"Botanical Garden"
#define SGPlaceCategoryHistoryMuseum @"History Museum"
#define SGPlaceCategoryObservatory @"Observatory"
#define SGPlaceCategoryScienceMuseum @"Science Museum"
#define SGPlaceCategoryZoo @"Zoo"
#define SGPlaceCategoryAmusementPark @"Amusement Park"
#define SGPlaceCategoryArcade @"Arcade"
#define SGPlaceCategoryBarbecue @"Barbecue"
#define SGPlaceCategoryBoatCharter @"Boat Charter"
#define SGPlaceCategoryCampground @"Campground"
#define SGPlaceCategoryDanceHall @"Dance Hall"
#define SGPlaceCategoryDogPark @"Dog Park"
#define SGPlaceCategoryFishing @"Fishing"
#define SGPlaceCategoryGardens @"Gardens"
#define SGPlaceCategoryGoKarts @"Go Karts"
#define SGPlaceCategoryGunRange @"Gun Range"
#define SGPlaceCategoryMarina @"Marina"
#define SGPlaceCategoryMiniatureGolf @"Miniature Golf"
#define SGPlaceCategoryPicnicArea @"Picnic Area"
#define SGPlaceCategoryPlayground @"Playground"
#define SGPlaceCategorySailingClub @"Sailing Club"
#define SGPlaceCategoryThemePark @"Theme Park"
#define SGPlaceCategoryWaterPark @"Water Park"
#define SGPlaceCategoryAthleticTrack @"Athletic Track"
#define SGPlaceCategoryBicycleRental @"Bicycle Rental"
#define SGPlaceCategoryBowling @"Bowling"
#define SGPlaceCategoryClimbingGym @"Climbing Gym"
#define SGPlaceCategoryGolf @"Golf"
#define SGPlaceCategoryGym @"Gym"
#define SGPlaceCategoryIceRink @"Ice Rink"
#define SGPlaceCategoryPlayingField @"Playing Field"
#define SGPlaceCategoryRaceTrack @"Race Track"
#define SGPlaceCategorySkatePark @"Skate Park"
#define SGPlaceCategorySkiResort @"Ski Resort"
#define SGPlaceCategorySkiSlope @"Ski Slope"
#define SGPlaceCategorySportsCenter @"Sports Center"
#define SGPlaceCategoryStables @"Stables"
#define SGPlaceCategorySwimmingPool @"Swimming Pool"
#define SGPlaceCategoryTennisCourt @"Tennis Court"
#define SGPlaceCategoryWinterSports @"Winter Sports"
#define SGPlaceCategoryBedAndBreakfast @"Bed & Breakfast"
#define SGPlaceCategoryChalets @"Chalets"
#define SGPlaceCategoryHostel @"Hostel"
#define SGPlaceCategoryHotelsAndMotels @"Hotels & Motels"
#define SGPlaceCategoryResort @"Resort"
#define SGPlaceCategoryTravelAgent @"Travel Agent"
#define SGPlaceCategoryBiergarten @"Biergarten"
#define SGPlaceCategoryChampagneBar @"Champagne Bar"
#define SGPlaceCategoryDiveBar @"Dive Bar"
#define SGPlaceCategoryGayBar @"Gay Bar"
#define SGPlaceCategoryHookahBar @"Hookah Bar"
#define SGPlaceCategoryLounge @"Lounge"
#define SGPlaceCategoryNightclub @"Nightclub"
#define SGPlaceCategoryOxygenBar @"Oxygen Bar"
#define SGPlaceCategorySportsBar @"Sports Bar"
#define SGPlaceCategoryWineBar @"Wine Bar"
#define SGPlaceCategoryAquaticFarm @"Aquatic Farm"
#define SGPlaceCategoryBerryFarm @"Berry Farm"
#define SGPlaceCategoryCrops @"Crops"
#define SGPlaceCategoryDairyFarm @"Dairy Farm"
#define SGPlaceCategoryFarm @"Farm"
#define SGPlaceCategoryFarmAndVeterinaryServices @"Farm & Veterinary Services"
#define SGPlaceCategoryFishAndMarineProducts @"Fish & Marine Products"
#define SGPlaceCategoryLivestockFarm @"Livestock Farm"
#define SGPlaceCategoryNursery @"Nursery"
#define SGPlaceCategoryOrchard @"Orchard"
#define SGPlaceCategoryPoultryFarm @"Poultry Farm"
#define SGPlaceCategoryVineyard @"Vineyard"
#define SGPlaceCategoryAerospace @"Aerospace"
#define SGPlaceCategoryApparel @"Apparel"
#define SGPlaceCategoryBuildingMaterials @"Building Materials"
#define SGPlaceCategoryBuildings @"Buildings"
#define SGPlaceCategoryChemicalsAndCompounds @"Chemicals & Compounds"
#define SGPlaceCategoryElectronics @"Electronics"
#define SGPlaceCategoryFood @"Food"
#define SGPlaceCategoryFurniture @"Furniture"
#define SGPlaceCategoryGlassAndMinerals @"Glass & Minerals"
#define SGPlaceCategoryJewelry @"Jewelry"
#define SGPlaceCategoryLeatherGoods @"Leather Goods"
#define SGPlaceCategoryLumber @"Lumber"
#define SGPlaceCategoryMetals @"Metals"
#define SGPlaceCategoryMotorVehiclesAndParts @"Motor Vehicles & Parts"
#define SGPlaceCategoryMusicalInstruments @"Musical Instruments"
#define SGPlaceCategoryPaperProducts @"Paper Products"
#define SGPlaceCategoryPetFood @"Pet Food"
#define SGPlaceCategoryPetroleumProducts @"Petroleum Products"
#define SGPlaceCategoryPottery @"Pottery"
#define SGPlaceCategoryPrinting @"Printing"
#define SGPlaceCategoryRetailGoods @"Retail Goods"
#define SGPlaceCategoryRubberAndPlastics @"Rubber & Plastics"
#define SGPlaceCategorySigns @"Signs"
#define SGPlaceCategorySoap @"Soap"
#define SGPlaceCategoryTextiles @"Textiles"
#define SGPlaceCategoryTobaccoProducts @"Tobacco Products"
#define SGPlaceCategoryToolsAndMachinery @"Tools & Machinery"
#define SGPlaceCategoryToysAndSportingGoods @"Toys & Sporting Goods"
#define SGPlaceCategoryWatercraft @"Watercraft"
#define SGPlaceCategoryWoodProducts @"Wood Products"
#define SGPlaceCategoryAutoParts @"Auto Parts"
#define SGPlaceCategoryBeer @"Beer"
#define SGPlaceCategoryBooksPeriodicalsAndNewspapers @"Books, Periodicals, & Newspapers"
#define SGPlaceCategoryChemicalsAndPlastics @"Chemicals & Plastics"
#define SGPlaceCategoryComputers @"Computers"
#define SGPlaceCategoryConstructionMaterials @"Construction Materials"
#define SGPlaceCategoryDairy @"Dairy"
#define SGPlaceCategoryDrugs @"Drugs"
#define SGPlaceCategoryDurableGoodsAndEquipment @"Durable Goods & Equipment"
#define SGPlaceCategoryElectrical @"Electrical"
#define SGPlaceCategoryFarmSupplies @"Farm Supplies"
#define SGPlaceCategoryFruitsAndVegetables @"Fruits & Vegetables"
#define SGPlaceCategoryGroceries @"Groceries"
#define SGPlaceCategoryHardware @"Hardware"
#define SGPlaceCategoryHomeFurnishings @"Home Furnishings"
#define SGPlaceCategoryMachineryAndSupplies @"Machinery & Supplies"
#define SGPlaceCategoryMeat @"Meat"
#define SGPlaceCategoryMedicalEquipmentAndSupplies @"Medical Equipment & Supplies"
#define SGPlaceCategoryMetalsAndMinerals @"Metals & Minerals"
#define SGPlaceCategoryMotorVehicles @"Motor Vehicles"
#define SGPlaceCategoryNonDurableGoods @"Non-Durable Goods"
#define SGPlaceCategoryOfficeEquipment @"Office Equipment"
#define SGPlaceCategoryPaintingSupplies @"Painting Supplies"
#define SGPlaceCategoryPetroleum @"Petroleum"
#define SGPlaceCategoryPhotographicEquipment @"Photographic Equipment"
#define SGPlaceCategoryPlants @"Plants"
#define SGPlaceCategoryPoultry @"Poultry"
#define SGPlaceCategoryScrap @"Scrap"
#define SGPlaceCategorySeafood @"Seafood"
#define SGPlaceCategorySportingGoods @"Sporting Goods"
#define SGPlaceCategoryStationery @"Stationery"
#define SGPlaceCategoryToysAndHobbies @"Toys & Hobbies"
#define SGPlaceCategoryVendingMachines @"Vending Machines"
#define SGPlaceCategoryWineAndDistilledAlcoholicBeverages @"Wine & Distilled Alcoholic Beverages"
#define SGPlaceCategoryMusicPublishers @"Music Publishers"
#define SGPlaceCategoryEthnic @"Ethnic"
#define SGPlaceCategorySenior @"Senior"
#define SGPlaceCategorySocial @"Social"
#define SGPlaceCategoryYouth @"Youth"
#define SGPlaceCategoryCollege @"College"
#define SGPlaceCategoryDanceStudio @"Dance Studio"
#define SGPlaceCategoryJuniorCollege @"Junior College"
#define SGPlaceCategoryKindergarten @"Kindergarten"
#define SGPlaceCategoryLibrary @"Library"
#define SGPlaceCategoryMusicSchool @"Music School"
#define SGPlaceCategoryPreschool @"Preschool"
#define SGPlaceCategorySchool @"School"
#define SGPlaceCategorySpecialTraining @"Special Training"
#define SGPlaceCategoryUniversity @"University"
#define SGPlaceCategoryVocationalSchool @"Vocational School"
#define SGPlaceCategoryCityHall @"City Hall"
#define SGPlaceCategoryCourtHouse @"Court House"
#define SGPlaceCategoryCustomsHouse @"Customs House"
#define SGPlaceCategoryDepartmentofMotorVehicles @"Department of Motor Vehicles"
#define SGPlaceCategoryEmbassy @"Embassy"
#define SGPlaceCategoryFireStation @"Fire Station"
#define SGPlaceCategoryJail @"Jail"
#define SGPlaceCategoryOffice @"Office"
#define SGPlaceCategoryPalace @"Palace"
#define SGPlaceCategoryPoliceStation @"Police Station"
#define SGPlaceCategoryPostOffice @"Post Office"
#define SGPlaceCategoryPrison @"Prison"
#define SGPlaceCategoryArchaeologicalSite @"Archaeological Site"
#define SGPlaceCategoryBattlefield @"Battlefield"
#define SGPlaceCategoryCastle @"Castle"
#define SGPlaceCategoryCityWalls @"City Walls"
#define SGPlaceCategoryFort @"Fort"
#define SGPlaceCategoryFountain @"Fountain"
#define SGPlaceCategoryHistoric @"Historic"
#define SGPlaceCategoryMarketplace @"Marketplace"
#define SGPlaceCategoryMemorial @"Memorial"
#define SGPlaceCategoryMonument @"Monument"
#define SGPlaceCategoryPlaza @"Plaza"
#define SGPlaceCategoryRuins @"Ruins"
#define SGPlaceCategoryScenicView @"Scenic View"
#define SGPlaceCategorySquare @"Square"
#define SGPlaceCategoryTouristAttraction @"Tourist Attraction"
#define SGPlaceCategoryTouristInformation @"Tourist Information"
#define SGPlaceCategoryUNESCOWorldHeritageSite @"UNESCO World Heritage Site"
#define SGPlaceCategoryAirForceBase @"Air Force Base"
#define SGPlaceCategoryAirfield @"Airfield"
#define SGPlaceCategoryArmory @"Armory"
#define SGPlaceCategoryArmyBase @"Army Base"
#define SGPlaceCategoryBarracks @"Barracks"
#define SGPlaceCategoryBunker @"Bunker"
#define SGPlaceCategoryCoastGuardBase @"Coast Guard Base"
#define SGPlaceCategoryNavalBase @"Naval Base"
#define SGPlaceCategoryRestrictedArea @"Restricted Area"
#define SGPlaceCategoryCounty @"County"
#define SGPlaceCategoryMunicipal @"Municipal"
#define SGPlaceCategoryNational @"National"
#define SGPlaceCategoryProvincial @"Provincial"
#define SGPlaceCategoryTownCommon @"Town Common"
#define SGPlaceCategoryChurch @"Church"
#define SGPlaceCategoryMonastery @"Monastery"
#define SGPlaceCategoryMosque @"Mosque"
#define SGPlaceCategoryShrine @"Shrine"
#define SGPlaceCategorySynagogue @"Synagogue"
#define SGPlaceCategoryTemple @"Temple"
#define SGPlaceCategoryBridge @"Bridge"
#define SGPlaceCategoryBuilding @"Building"
#define SGPlaceCategoryFactory @"Factory"
#define SGPlaceCategoryHistoricBuilding @"Historic Building"
#define SGPlaceCategoryOfficeBuilding @"Office Building"
#define SGPlaceCategoryPublicBuilding @"Public Building"
#define SGPlaceCategoryRestrooms @"Restrooms"
#define SGPlaceCategoryShoppingMall @"Shopping Mall"
#define SGPlaceCategoryTower @"Tower"
#define SGPlaceCategoryTunnel @"Tunnel"
#define SGPlaceCategoryWarehouse @"Warehouse"
#define SGPlaceCategoryAutoSupplies @"Auto Supplies"
#define SGPlaceCategoryAutomobileSales @"Automobile Sales"
#define SGPlaceCategoryBoatSales @"Boat Sales"
#define SGPlaceCategoryFuelAndGasStation @"Fuel & Gas Station"
#define SGPlaceCategoryMotorcycleSales @"Motorcycle Sales"
#define SGPlaceCategoryRecreationalVehicleSales @"Recreational Vehicle Sales"
#define SGPlaceCategoryBakery @"Bakery"
#define SGPlaceCategoryCandy @"Candy"
#define SGPlaceCategoryCheese @"Cheese"
#define SGPlaceCategoryChocolate @"Chocolate"
#define SGPlaceCategoryEthnicFoods @"Ethnic Foods"
#define SGPlaceCategoryFarmersMarket @"Farmers Market"
#define SGPlaceCategoryGroceriesAndConvenienceStores @"Groceries & Convenience Stores"
#define SGPlaceCategoryLiquorAndBeverages @"Liquor & Beverages"
#define SGPlaceCategoryMeatAndFish @"Meat & Fish"
#define SGPlaceCategorySpecialty @"Specialty"
#define SGPlaceCategorySupermarket @"Supermarket"
#define SGPlaceCategoryCarpetsAndFloorCoverings @"Carpets & Floor Coverings"
#define SGPlaceCategoryGardenSupply @"Garden Supply"
#define SGPlaceCategoryHouseholdAppliances @"Household Appliances"
#define SGPlaceCategoryKitchenSupply @"Kitchen Supply"
#define SGPlaceCategoryMobileHomes @"Mobile Homes"
#define SGPlaceCategoryAdult @"Adult"
#define SGPlaceCategoryAntiques @"Antiques"
#define SGPlaceCategoryBabyStore @"Baby Store"
#define SGPlaceCategoryBeautyAndCosmetics @"Beauty & Cosmetics"
#define SGPlaceCategoryBicyclesAndSportingGoods @"Bicycles & Sporting Goods"
#define SGPlaceCategoryBooks @"Books"
#define SGPlaceCategoryBridal @"Bridal"
#define SGPlaceCategoryCatalogStore @"Catalog Store"
#define SGPlaceCategoryClothingApparelAndFashions @"Clothing, Apparel, & Fashions"
#define SGPlaceCategoryComicBooks @"Comic Books"
#define SGPlaceCategoryComputersAndHomeElectronics @"Computers & Home Electronics"
#define SGPlaceCategoryCraftsAndFabrics @"Crafts & Fabrics"
#define SGPlaceCategoryDepartmentStore @"Department Store"
#define SGPlaceCategoryDiscountAndVarietyStores @"Discount & Variety Stores"
#define SGPlaceCategoryEventTickets @"Event Tickets"
#define SGPlaceCategoryFlorist @"Florist"
#define SGPlaceCategoryGiftsAndSouvenirs @"Gifts & Souvenirs"
#define SGPlaceCategoryHobbiesToysAndGames @"Hobbies, Toys, & Games"
#define SGPlaceCategoryLuggageAndLeatherGoods @"Luggage & Leather Goods"
#define SGPlaceCategoryMobilePhones @"Mobile Phones"
#define SGPlaceCategoryNews @"News"
#define SGPlaceCategoryOpticalGoods @"Optical Goods"
#define SGPlaceCategoryOptician @"Optician"
#define SGPlaceCategoryPartySupplies @"Party Supplies"
#define SGPlaceCategoryPawnShop @"Pawn Shop"
#define SGPlaceCategoryPetsAndPetSupplies @"Pets & Pet Supplies"
#define SGPlaceCategoryPharmacy @"Pharmacy"
#define SGPlaceCategoryShoes @"Shoes"
#define SGPlaceCategoryStationeryAndOfficeSupplies @"Stationery & Office Supplies"
#define SGPlaceCategoryThriftStore @"Thrift Store"
#define SGPlaceCategoryTobacco @"Tobacco"
#define SGPlaceCategoryUsedMerchandise @"Used Merchandise"
#define SGPlaceCategoryATM @"ATM"
#define SGPlaceCategoryBank @"Bank"
#define SGPlaceCategoryBureaudeChange @"Bureau de Change"
#define SGPlaceCategoryFinancialServices @"Financial Services"
#define SGPlaceCategoryInvestmentBrokerage @"Investment Brokerage"
#define SGPlaceCategoryPestControl @"Pest Control"
#define SGPlaceCategoryCleaningAndSanitation @"Cleaning & Sanitation"
#define SGPlaceCategoryConstruction @"Construction"
#define SGPlaceCategoryEquipmentRental @"Equipment Rental"
#define SGPlaceCategoryLandfill @"Landfill"
#define SGPlaceCategoryLandscapingServices @"Landscaping Services"
#define SGPlaceCategoryLocksmith @"Locksmith"
#define SGPlaceCategoryPlumbing @"Plumbing"
#define SGPlaceCategoryFilmAndVideoProduction @"Film & Video Production"
#define SGPlaceCategoryNewsServices @"News Services"
#define SGPlaceCategoryNewspaper @"Newspaper"
#define SGPlaceCategoryRadioStation @"Radio Station"
#define SGPlaceCategoryTelevisionStation @"Television Station"
#define SGPlaceCategoryChiropractor @"Chiropractor"
#define SGPlaceCategoryClinic @"Clinic"
#define SGPlaceCategoryDentist @"Dentist"
#define SGPlaceCategoryDoctor @"Doctor"
#define SGPlaceCategoryHealthPractitioner @"Health Practitioner"
#define SGPlaceCategoryHospice @"Hospice"
#define SGPlaceCategoryHospital @"Hospital"
#define SGPlaceCategoryMedicalLab @"Medical Lab"
#define SGPlaceCategoryNursingandCareFacility @"Nursing and Care Facility"
#define SGPlaceCategoryOptometrist @"Optometrist"
#define SGPlaceCategoryPodiatrist @"Podiatrist"
#define SGPlaceCategoryHazardInsurance @"Hazard Insurance"
#define SGPlaceCategoryHealthInsurance @"Health Insurance"
#define SGPlaceCategoryInsuranceAgent @"Insurance Agent"
#define SGPlaceCategoryLifeInsurance @"Life Insurance"
#define SGPlaceCategoryTitleInsurance @"Title Insurance"
#define SGPlaceCategoryCommunityAssociation @"Community Association"
#define SGPlaceCategoryLaborOrganization @"Labor Organization"
#define SGPlaceCategoryMembershipOrganization @"Membership Organization"
#define SGPlaceCategoryNonProfitOrganization @"Non-Profit Organization"
#define SGPlaceCategoryPoliticalOrganization @"Political Organization"
#define SGPlaceCategoryProfessionalAssociation @"Professional Association"
#define SGPlaceCategoryReligiousOrganization @"Religious Organization"
#define SGPlaceCategoryBarber @"Barber"
#define SGPlaceCategoryBeautySalon @"Beauty Salon"
#define SGPlaceCategoryDaySpa @"Day Spa"
#define SGPlaceCategoryHairRemoval @"Hair Removal"
#define SGPlaceCategoryMassage @"Massage"
#define SGPlaceCategoryNailSalon @"Nail Salon"
#define SGPlaceCategoryPiercing @"Piercing"
#define SGPlaceCategoryPsychicsAndAstrologers @"Psychics & Astrologers"
#define SGPlaceCategorySauna @"Sauna"
#define SGPlaceCategoryShoeRepairAndShine @"Shoe Repair & Shine"
#define SGPlaceCategorySkinCare @"Skin Care"
#define SGPlaceCategoryTanningParlor @"Tanning Parlor"
#define SGPlaceCategoryTattooParlor @"Tattoo Parlor"
#define SGPlaceCategoryAccountingAndTaxPreparation @"Accounting & Tax Preparation"
#define SGPlaceCategoryAdvertising @"Advertising"
#define SGPlaceCategoryArtServices @"Art Services"
#define SGPlaceCategoryBusinessServices @"Business Services"
#define SGPlaceCategoryComputerServices @"Computer Services"
#define SGPlaceCategoryCreditReportingAndCollection @"Credit Reporting & Collection"
#define SGPlaceCategoryDetectiveAndSecurityServices @"Detective & Security Services"
#define SGPlaceCategoryEmploymentAgencies @"Employment Agencies"
#define SGPlaceCategoryEngineering @"Engineering"
#define SGPlaceCategoryLawyerAndLegalServices @"Lawyer & Legal Services"
#define SGPlaceCategoryManagementAndConsulting @"Management & Consulting"
#define SGPlaceCategoryPrintingAndPhotocopies @"Printing & Photocopies"
#define SGPlaceCategoryResearch @"Research"
#define SGPlaceCategorySecretarialServices @"Secretarial Services"
#define SGPlaceCategoryTestingLab @"Testing Lab"
#define SGPlaceCategoryArchitect @"Architect"
#define SGPlaceCategoryDeveloper @"Developer"
#define SGPlaceCategoryRealEstateAgent @"Real Estate Agent"
#define SGPlaceCategoryRealEstateOperator @"Real Estate Operator"
#define SGPlaceCategoryRealEstateServices @"Real Estate Services"
#define SGPlaceCategorySurveying @"Surveying"
#define SGPlaceCategoryAnimalServices @"Animal Services"
#define SGPlaceCategoryAutoRental @"Auto Rental"
#define SGPlaceCategoryAutoRepair @"Auto Repair"
#define SGPlaceCategoryCarWash @"Car Wash"
#define SGPlaceCategoryDrivingSchool @"Driving School"
#define SGPlaceCategoryEventSpace @"Event Space"
#define SGPlaceCategoryFuneralServices @"Funeral Services"
#define SGPlaceCategoryLaundryAndDryCleaning @"Laundry & Dry Cleaning"
#define SGPlaceCategoryPetBoarding @"Pet Boarding"
#define SGPlaceCategoryPhotofinishing @"Photofinishing"
#define SGPlaceCategoryPortraitStudio @"Portrait Studio"
#define SGPlaceCategoryRepairShop @"Repair Shop"
#define SGPlaceCategorySelfServiceLaundry @"Self-Service Laundry"
#define SGPlaceCategoryStorage @"Storage"
#define SGPlaceCategoryVeterinaryServices @"Veterinary Services"
#define SGPlaceCategoryEmissionsTesting @"Emissions Testing"
#define SGPlaceCategoryAdultCare @"Adult Care"
#define SGPlaceCategoryChildCare @"Child Care"
#define SGPlaceCategoryJobTraining @"Job Training"
#define SGPlaceCategoryRetirementHome @"Retirement Home"
#define SGPlaceCategoryCable @"Cable"
#define SGPlaceCategoryElectric @"Electric"
#define SGPlaceCategoryFuelOilAndLPG @"Fuel Oil & LPG"
#define SGPlaceCategoryMobilePhone @"Mobile Phone"
#define SGPlaceCategoryNaturalGas @"Natural Gas"
#define SGPlaceCategoryRecycling @"Recycling"
#define SGPlaceCategoryRefuse @"Refuse"
#define SGPlaceCategorySewage @"Sewage"
#define SGPlaceCategoryTelephone @"Telephone"
#define SGPlaceCategoryWater @"Water"
#define SGPlaceCategoryDomestic @"Domestic"
#define SGPlaceCategoryGeneralAviation @"General Aviation"
#define SGPlaceCategoryInternational @"International"
#define SGPlaceCategoryBus @"Bus"
#define SGPlaceCategoryTrain @"Train"
#define SGPlaceCategoryBicycle @"Bicycle"
#define SGPlaceCategoryGarage @"Garage"
#define SGPlaceCategoryLot @"Lot"
#define SGPlaceCategoryLightRail @"Light Rail"
#define SGPlaceCategoryRail @"Rail"
#define SGPlaceCategoryFreight @"Freight"
#define SGPlaceCategoryPassenger @"Passenger"

#pragma mark -
#pragma mark Places Categories (Places 1.2)

// TODO